[package]
name = "aster_forge_webdav"
version = "0.1.0-beta.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[features]
default = []
actix = ["dep:actix-web"]

[dependencies]
actix-web = { workspace = true, optional = true }
aster_forge_utils = { path = "../aster_forge_utils" }
aster_forge_xml = { path = "../aster_forge_xml" }
async-trait.workspace = true
bytes.workspace = true
chrono = { workspace = true, features = ["clock"] }
futures.workspace = true
headers.workspace = true
http.workspace = true
percent-encoding.workspace = true
thiserror.workspace = true

[lints]
workspace = true
