//! UUID and token generation helpers.
//!
//! The module provides plain random tokens as well as retry helpers for business-unique UUIDs.
//! Callers remain responsible for enforcing uniqueness at the database layer, but the helpers
//! centralize collision retry loops and error messages.

use std::future::Future;

use crate::{Result, UtilsError};
use uuid::Uuid;

/// Maximum number of UUID candidates generated by unique UUID helpers.
pub const UNIQUE_UUID_MAX_ATTEMPTS: usize = 5;

/// Result of attempting to reserve or accept a generated UUID.
pub enum UniqueUuidAttempt<T> {
    /// Candidate was accepted and produced a value.
    Accepted(T),
    /// Candidate collided and should be retried with a new UUID.
    Collision,
}

/// Generates a UUID v4 string.
pub fn new_uuid() -> String {
    Uuid::new_v4().to_string()
}

/// Runs an operation with a business-unique UUID and retries on reported collisions.
pub async fn with_unique_uuid<F, Fut, T>(value_name: &str, mut try_candidate: F) -> Result<T>
where
    F: FnMut(Uuid) -> Fut,
    Fut: Future<Output = Result<UniqueUuidAttempt<T>>>,
{
    for attempt in 1..=UNIQUE_UUID_MAX_ATTEMPTS {
        let candidate = Uuid::new_v4();
        match try_candidate(candidate).await? {
            UniqueUuidAttempt::Accepted(value) => return Ok(value),
            UniqueUuidAttempt::Collision => {
                tracing::warn!(
                    value_name,
                    attempt,
                    candidate = %candidate,
                    "uuid collision, retrying"
                );
            }
        }
    }

    Err(UtilsError::invalid_value(format!(
        "failed to create unique {value_name} UUID after {UNIQUE_UUID_MAX_ATTEMPTS} attempts"
    )))
}

/// Generates a business UUID and filters occupied candidates through caller-provided lookup.
///
/// This helper does not atomically reserve the value; callers must still rely on a database
/// uniqueness constraint in the later write path. Use [`with_unique_uuid`] when check-and-reserve
/// semantics are needed, and perform the write inside the callback.
pub async fn new_best_effort_uuid<F, Fut>(value_name: &str, mut is_taken: F) -> Result<Uuid>
where
    F: FnMut(Uuid) -> Fut,
    Fut: Future<Output = Result<bool>>,
{
    with_unique_uuid(value_name, |candidate| {
        let taken = is_taken(candidate);
        async move {
            if taken.await? {
                Ok(UniqueUuidAttempt::Collision)
            } else {
                Ok(UniqueUuidAttempt::Accepted(candidate))
            }
        }
    })
    .await
}

/// Generates a short 32-character hex token.
pub fn new_short_token() -> String {
    Uuid::new_v4().simple().to_string()
}

/// Generates a 32-character UUID v4 hex token for share links.
pub fn new_share_token() -> String {
    Uuid::new_v4().simple().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{
        Arc,
        atomic::{AtomicUsize, Ordering},
    };

    #[tokio::test]
    async fn new_best_effort_uuid_returns_first_free_candidate() {
        let attempts = Arc::new(AtomicUsize::new(0));
        let result = new_best_effort_uuid("test value", {
            let attempts = Arc::clone(&attempts);
            move |_| {
                let attempts = Arc::clone(&attempts);
                async move {
                    attempts.fetch_add(1, Ordering::SeqCst);
                    Ok(false)
                }
            }
        })
        .await;

        assert!(result.is_ok());
        assert_eq!(attempts.load(Ordering::SeqCst), 1);
    }

    #[tokio::test]
    async fn with_unique_uuid_retries_collisions_and_returns_callback_value() {
        let attempts = Arc::new(AtomicUsize::new(0));
        let result: String = with_unique_uuid("test value", {
            let attempts = Arc::clone(&attempts);
            move |candidate| {
                let attempts = Arc::clone(&attempts);
                async move {
                    let attempt = attempts.fetch_add(1, Ordering::SeqCst);
                    if attempt < 2 {
                        Ok(UniqueUuidAttempt::Collision)
                    } else {
                        Ok(UniqueUuidAttempt::Accepted(candidate.to_string()))
                    }
                }
            }
        })
        .await
        .expect("third candidate should be accepted");

        assert!(Uuid::parse_str(&result).is_ok());
        assert_eq!(attempts.load(Ordering::SeqCst), 3);
    }

    #[tokio::test]
    async fn with_unique_uuid_propagates_callback_errors_without_retrying() {
        let attempts = Arc::new(AtomicUsize::new(0));
        let result: Result<String> = with_unique_uuid("test value", {
            let attempts = Arc::clone(&attempts);
            move |_| {
                let attempts = Arc::clone(&attempts);
                async move {
                    attempts.fetch_add(1, Ordering::SeqCst);
                    Err(UtilsError::invalid_value("candidate check failed"))
                }
            }
        })
        .await;

        let error = result.expect_err("callback error should be returned");
        assert!(matches!(error, UtilsError::InvalidValue(_)));
        assert_eq!(attempts.load(Ordering::SeqCst), 1);
    }

    #[tokio::test]
    async fn new_best_effort_uuid_retries_taken_candidates() {
        let attempts = Arc::new(AtomicUsize::new(0));
        let result = new_best_effort_uuid("test value", {
            let attempts = Arc::clone(&attempts);
            move |_| {
                let attempts = Arc::clone(&attempts);
                async move {
                    let attempt = attempts.fetch_add(1, Ordering::SeqCst);
                    Ok(attempt < 2)
                }
            }
        })
        .await;

        assert!(result.is_ok());
        assert_eq!(attempts.load(Ordering::SeqCst), 3);
    }

    #[tokio::test]
    async fn new_best_effort_uuid_stops_after_retry_budget_is_exhausted() {
        let attempts = Arc::new(AtomicUsize::new(0));
        let result = new_best_effort_uuid("test value", {
            let attempts = Arc::clone(&attempts);
            move |_| {
                let attempts = Arc::clone(&attempts);
                async move {
                    attempts.fetch_add(1, Ordering::SeqCst);
                    Ok(true)
                }
            }
        })
        .await;

        let error = result.expect_err("all candidates were reported as taken");
        assert!(matches!(error, UtilsError::InvalidValue(_)));
        assert_eq!(attempts.load(Ordering::SeqCst), UNIQUE_UUID_MAX_ATTEMPTS);
    }

    #[test]
    fn new_share_token_uses_uuid_v4_hex_entropy() {
        let token = new_share_token();

        assert_eq!(token.len(), 32);
        assert!(!token.contains('-'));
        assert!(Uuid::parse_str(&token).is_ok());
    }
}
