use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_orm::DatabaseBackend;

const MYSQL_UTC_DATETIME_TYPE: &str = "datetime(6)";

/// Builds the conventional signed 64-bit auto-incrementing primary-key column.
pub fn big_integer_primary_key<T>(column: T) -> ColumnDef
where
    T: IntoIden,
{
    let mut column = ColumnDef::new(column);
    column
        .big_integer()
        .not_null()
        .auto_increment()
        .primary_key();
    column
}

/// Builds a UTC datetime column for the schema manager's backend.
pub fn utc_date_time_column<T>(manager: &SchemaManager<'_>, column: T) -> ColumnDef
where
    T: IntoIden,
{
    utc_date_time_column_for_backend(manager.get_database_backend(), column)
}

/// Builds a UTC datetime column for an explicit database backend.
pub fn utc_date_time_column_for_backend<T>(backend: DatabaseBackend, column: T) -> ColumnDef
where
    T: IntoIden,
{
    let mut column = ColumnDef::new(column);

    match backend {
        DatabaseBackend::MySql => {
            column.custom(Alias::new(MYSQL_UTC_DATETIME_TYPE));
        }
        _ => {
            column.timestamp_with_time_zone();
        }
    }

    column
}

/// Builds a non-null JSON-text column for a migration's final schema.
///
/// `MySQL` TEXT defaults are omitted for compatibility; `PostgreSQL` and `SQLite` receive `{}`.
pub fn json_text_column_for_final_schema<T: IntoIden>(
    manager: &SchemaManager<'_>,
    name: T,
) -> ColumnDef {
    json_text_column_for_final_schema_backend(manager.get_database_backend(), name)
}

fn json_text_column_for_final_schema_backend<T: IntoIden>(
    backend: DatabaseBackend,
    name: T,
) -> ColumnDef {
    let mut column = ColumnDef::new(name);
    column.text();

    if backend == DatabaseBackend::MySql {
        column.not_null();
    } else {
        column.not_null().default("{}");
    }

    column
}

/// Builds a nullable JSON-text column suitable for a later data backfill.
pub fn nullable_json_text_column_for_backfill<T: IntoIden>(name: T) -> ColumnDef {
    let mut column = ColumnDef::new(name);
    column.text().null();
    column
}

#[cfg(test)]
mod tests {
    use sea_orm_migration::sea_query::{
        MysqlQueryBuilder, PostgresQueryBuilder, SqliteQueryBuilder,
    };

    use super::*;

    #[derive(DeriveIden)]
    enum ExampleTable {
        Table,
        Id,
        ExpiresAt,
        Options,
    }

    #[test]
    fn big_integer_primary_key_has_the_same_contract_on_all_backends() {
        for backend in [
            DatabaseBackend::MySql,
            DatabaseBackend::Postgres,
            DatabaseBackend::Sqlite,
        ] {
            let sql = create_table_sql(backend, big_integer_primary_key(ExampleTable::Id));
            let normalized = sql.to_ascii_lowercase();
            assert!(normalized.contains("not null"), "{sql}");
            assert!(normalized.contains("primary key"), "{sql}");
            match backend {
                DatabaseBackend::MySql => {
                    assert!(normalized.contains("bigint"), "{sql}");
                    assert!(normalized.contains("auto_increment"), "{sql}");
                }
                DatabaseBackend::Postgres => {
                    assert!(normalized.contains("bigint"), "{sql}");
                    assert!(
                        normalized.contains("generated by default as identity"),
                        "{sql}"
                    );
                }
                DatabaseBackend::Sqlite => assert!(normalized.contains("integer"), "{sql}"),
                _ => unreachable!("unsupported backend in migration schema helper test"),
            }
        }
    }

    fn create_table_sql(backend: DatabaseBackend, column: ColumnDef) -> String {
        let table = Table::create()
            .table(ExampleTable::Table)
            .col(column)
            .to_owned();

        match backend {
            DatabaseBackend::MySql => table.to_string(MysqlQueryBuilder),
            DatabaseBackend::Postgres => table.to_string(PostgresQueryBuilder),
            DatabaseBackend::Sqlite => table.to_string(SqliteQueryBuilder),
            _ => unreachable!("unsupported backend in migration schema helper test"),
        }
    }

    #[test]
    fn utc_datetime_columns_respect_backend_types() {
        let mysql = create_table_sql(
            DatabaseBackend::MySql,
            utc_date_time_column_for_backend(DatabaseBackend::MySql, ExampleTable::ExpiresAt)
                .not_null()
                .to_owned(),
        );
        assert!(mysql.contains("datetime(6) NOT NULL"));

        let postgres = create_table_sql(
            DatabaseBackend::Postgres,
            utc_date_time_column_for_backend(DatabaseBackend::Postgres, ExampleTable::ExpiresAt)
                .not_null()
                .to_owned(),
        );
        assert!(postgres.contains("timestamp with time zone NOT NULL"));

        let sqlite = create_table_sql(
            DatabaseBackend::Sqlite,
            utc_date_time_column_for_backend(DatabaseBackend::Sqlite, ExampleTable::ExpiresAt)
                .not_null()
                .to_owned(),
        );
        assert!(sqlite.contains("timestamp_with_timezone_text NOT NULL"));
    }

    #[test]
    fn json_text_final_schema_uses_portable_defaults() {
        let mysql = create_table_sql(
            DatabaseBackend::MySql,
            json_text_column_for_final_schema_backend(
                DatabaseBackend::MySql,
                ExampleTable::Options,
            ),
        );
        assert!(mysql.contains("text NOT NULL"));
        assert!(!mysql.contains("DEFAULT"));

        for backend in [DatabaseBackend::Postgres, DatabaseBackend::Sqlite] {
            let sql = create_table_sql(
                backend,
                json_text_column_for_final_schema_backend(backend, ExampleTable::Options),
            );
            assert!(sql.contains("NOT NULL"));
            assert!(sql.contains("DEFAULT '{}'"));
        }
    }

    #[test]
    fn nullable_json_backfill_column_stays_nullable() {
        let sql = create_table_sql(
            DatabaseBackend::Postgres,
            nullable_json_text_column_for_backfill(ExampleTable::Options),
        );
        assert!(!sql.contains("NOT NULL"));
    }
}
