//! API response models.

use serde::Serialize;

/// Basic health response returned by the generated skeleton.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(all(debug_assertions, feature = "openapi"), derive(utoipa::ToSchema))]
pub struct HealthResponse {
    /// Cache backend selected during startup.
    pub cache_backend: &'static str,
    /// Whether config sync has an enabled cross-process notifier.
    pub config_sync_enabled: bool,
    /// Runtime instance ID generated by Forge config sync.
    pub runtime_id: String,
    /// Cargo package name.
    pub service: &'static str,
    /// Health status.
    pub status: &'static str,
}

/// Readiness response returned by `/readyz`.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(all(debug_assertions, feature = "openapi"), derive(utoipa::ToSchema))]
pub struct ReadinessResponse {
    /// Component reports collected during the readiness check.
    pub components: Vec<ReadinessComponent>,
    /// Cargo package name.
    pub service: &'static str,
    /// Aggregate readiness status.
    pub status: &'static str,
}

/// Readiness status for a single runtime dependency.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(all(debug_assertions, feature = "openapi"), derive(utoipa::ToSchema))]
pub struct ReadinessComponent {
    /// Component name.
    pub name: &'static str,
    /// Component status.
    pub status: &'static str,
    /// Human-readable status message.
    pub message: String,
}
